import type { Metadata } from "next";
import "./globals.css"
import { ToastContainer } from "react-toastify";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="h-screen w-screen font-iranYekan">
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
