import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import MainSesseionProvider from "../providers/SesseionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const iranyekkan = localFont({
  src: [
    {
      path: "../public/fonts/iranyekanwebblack.woff",
      style: "normal",
      weight: "900",
    },
    {
      path: "../public/fonts/iranyekanwebbold.woff",
      style: "normal",
      weight: "700",
    },
    {
      path: "../public/fonts/iranyekanwebextrablack.woff",
      style: "normal",
      weight: "800",
    },
    {
      path: "../public/fonts/iranyekanwebextrabold.woff",
      style: "normal",
      weight: "600",
    },
    {
      path: "../public/fonts/iranyekanweblight.woff",
      style: "normal",
      weight: "300",
    },
    {
      path: "../public/fonts/iranyekanwebmedium.woff",
      style: "normal",
      weight: "500",
    },
    {
      path: "../public/fonts/iranyekanwebregular.woff",
      style: "normal",
      weight: "400",
    },
    {
      path: "../public/fonts/iranyekanwebthin.woff",
      style: "normal",
      weight: "100",
    },
  ],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`h-screen w-screen ${iranyekkan.className}`}>
        <MainSesseionProvider>
          {children}
          <ToastContainer />
        </MainSesseionProvider>
      </body>
    </html>
  );
}
